[package]
name = "Fortuna"
version = "1.0.0"
authors = []

[addresses]
fortuna_addr = "0x1234"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
