[package]
name = "Fortuna"
version = "1.0.0"
authors = []

[addresses]
fortuna_addr = "0xe6ccfea74c4481b3ca2fa1f7056273dba12483e39562839dc704a3e1fd9e559f"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }

[dev-dependencies]
